name: SL Scan

on: push

jobs:
  Scan-Build:
    # Scan runs on ubuntu, mac and windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      with:
        output: reports

    - name: Upload report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: reports
